### ISSUE TITLE
Websocket closes after some time, how to re-open it?

### ISSUE THREAD

**Issue by GGORG0** [xaronnn/js-lanyard#4]
It works for some time, but then suddenly I start getting errors.

![image](https://user-images.githubusercontent.com/51029895/154257746-18bf62e6-54eb-4985-9070-102eba8db375.png)

**Comment by GGORG0** [comment]
You can see it on my website, where it updates the discord and spotify status if it doesn't work for you. https://ggorg.tk

**Comment by xaronnn** [comment]
I just investigated that problem, i think region-based connectivity timeout. No any timeout, errors on another js-lanyard users.
